---
name: VipKit
author: JUZEXMOD\DevolperPHP
main: VipKit\vipkit
version: 1.0
api: [2.0.0]

commands
  kitvip:
    description: Kitvip Command
    use: "/kitvip"
    permission: vipkit.kitvip
    
permission:
  vipkit.kitvip:
    description: "Kitvip Command"
    default: op
